# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: color.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='color.proto',
  package='feed.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x63olor.proto\x12\x07\x66\x65\x65\x64.v1\"\x14\n\x05\x43olor\x12\x0b\n\x03hex\x18\x01 \x01(\t\"\x11\n\x0fNewColorRequest2B\n\x0e\x43olorGenerator\x12\x30\n\x04Next\x12\x18.feed.v1.NewColorRequest\x1a\x0e.feed.v1.ColorB\x08Z\x06\x66\x65\x65\x64pbb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COLOR = _descriptor.Descriptor(
  name='Color',
  full_name='feed.v1.Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hex', full_name='feed.v1.Color.hex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)


_NEWCOLORREQUEST = _descriptor.Descriptor(
  name='NewColorRequest',
  full_name='feed.v1.NewColorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['Color'] = _COLOR
DESCRIPTOR.message_types_by_name['NewColorRequest'] = _NEWCOLORREQUEST

Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), dict(
  DESCRIPTOR = _COLOR,
  __module__ = 'color_pb2'
  # @@protoc_insertion_point(class_scope:feed.v1.Color)
  ))
_sym_db.RegisterMessage(Color)

NewColorRequest = _reflection.GeneratedProtocolMessageType('NewColorRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEWCOLORREQUEST,
  __module__ = 'color_pb2'
  # @@protoc_insertion_point(class_scope:feed.v1.NewColorRequest)
  ))
_sym_db.RegisterMessage(NewColorRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006feedpb'))
# @@protoc_insertion_point(module_scope)
