# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feedprovider.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='feedprovider.proto',
  package='feed.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x66\x65\x65\x64provider.proto\x12\x07\x66\x65\x65\x64.v1\x1a\x0c\x63ommon.proto\">\n\x12ProviderGetRequest\x12(\n\x07request\x18\x01 \x01(\x0b\x32\x17.feed.v1.FeedGetRequest2L\n\x0c\x46\x65\x65\x64Provider\x12<\n\x03Get\x12\x1b.feed.v1.ProviderGetRequest\x1a\x18.feed.v1.FeedGetResponseB\x08Z\x06\x66\x65\x65\x64pbb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROVIDERGETREQUEST = _descriptor.Descriptor(
  name='ProviderGetRequest',
  full_name='feed.v1.ProviderGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='feed.v1.ProviderGetRequest.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=107,
)

_PROVIDERGETREQUEST.fields_by_name['request'].message_type = common__pb2._FEEDGETREQUEST
DESCRIPTOR.message_types_by_name['ProviderGetRequest'] = _PROVIDERGETREQUEST

ProviderGetRequest = _reflection.GeneratedProtocolMessageType('ProviderGetRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROVIDERGETREQUEST,
  __module__ = 'feedprovider_pb2'
  # @@protoc_insertion_point(class_scope:feed.v1.ProviderGetRequest)
  ))
_sym_db.RegisterMessage(ProviderGetRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006feedpb'))
# @@protoc_insertion_point(module_scope)
