// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feedprovider.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Feed.V1 {

  /// <summary>Holder for reflection information generated from feedprovider.proto</summary>
  public static partial class FeedproviderReflection {

    #region Descriptor
    /// <summary>File descriptor for feedprovider.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FeedproviderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJmZWVkcHJvdmlkZXIucHJvdG8SB2ZlZWQudjEaDGNvbW1vbi5wcm90byI+",
            "ChJQcm92aWRlckdldFJlcXVlc3QSKAoHcmVxdWVzdBgBIAEoCzIXLmZlZWQu",
            "djEuRmVlZEdldFJlcXVlc3QyTAoMRmVlZFByb3ZpZGVyEjwKA0dldBIbLmZl",
            "ZWQudjEuUHJvdmlkZXJHZXRSZXF1ZXN0GhguZmVlZC52MS5GZWVkR2V0UmVz",
            "cG9uc2VCCFoGZmVlZHBiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Feed.V1.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Feed.V1.ProviderGetRequest), global::Feed.V1.ProviderGetRequest.Parser, new[]{ "Request" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProviderGetRequest : pb::IMessage<ProviderGetRequest> {
    private static readonly pb::MessageParser<ProviderGetRequest> _parser = new pb::MessageParser<ProviderGetRequest>(() => new ProviderGetRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProviderGetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Feed.V1.FeedproviderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProviderGetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProviderGetRequest(ProviderGetRequest other) : this() {
      Request = other.request_ != null ? other.Request.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProviderGetRequest Clone() {
      return new ProviderGetRequest(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private global::Feed.V1.FeedGetRequest request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Feed.V1.FeedGetRequest Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProviderGetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProviderGetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProviderGetRequest other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          request_ = new global::Feed.V1.FeedGetRequest();
        }
        Request.MergeFrom(other.Request);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (request_ == null) {
              request_ = new global::Feed.V1.FeedGetRequest();
            }
            input.ReadMessage(request_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
