# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newsfeed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='newsfeed.proto',
  package='feed.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0enewsfeed.proto\x12\x07\x66\x65\x65\x64.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x0c\x63ommon.proto2Z\n\x08NewsFeed\x12N\n\x03Get\x12\x17.feed.v1.FeedGetRequest\x1a\x18.feed.v1.FeedGetResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/feed/v1/getB\x08Z\x06\x66\x65\x65\x64pbb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006feedpb'))
# @@protoc_insertion_point(module_scope)
