// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Feed.V1 {

  /// <summary>Holder for reflection information generated from newsfeed.proto</summary>
  public static partial class NewsfeedReflection {

    #region Descriptor
    /// <summary>File descriptor for newsfeed.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NewsfeedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5uZXdzZmVlZC5wcm90bxIHZmVlZC52MRocZ29vZ2xlL2FwaS9hbm5vdGF0",
            "aW9ucy5wcm90bxoMY29tbW9uLnByb3RvMloKCE5ld3NGZWVkEk4KA0dldBIX",
            "LmZlZWQudjEuRmVlZEdldFJlcXVlc3QaGC5mZWVkLnYxLkZlZWRHZXRSZXNw",
            "b25zZSIUgtPkkwIOEgwvZmVlZC92MS9nZXRCCFoGZmVlZHBiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Feed.V1.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
