apiVersion: v1
kind: Service
metadata:
  labels:
    app: color-generator
  name: color-generator
  namespace: default
spec:
  ports:
  - name: grpc
    port: 4000
  selector:
    app: color-generator
  type: ClusterIP
