apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-aggregator
  name: feed-aggregator
  namespace: default
spec:
  ports:
  - name: grpc
    port: 3010
  selector:
    app: feed-aggregator
  type: ClusterIP
