apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-python
  name: feed-python
  namespace: default
spec:
  ports:
  - name: groc
    port: 3040
  selector:
    app: feed-python
  type: ClusterIP
