apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: feed-python
  name: feed-python
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "20%"
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: feed-python
      name: feed-python
    spec:
      containers:
      - env:
        - name: COLOR_SERVER
          value: color-generator.default:4000
        image: sercand/demo-feed-python:1.16
        imagePullPolicy: IfNotPresent
        name: feed-python
        ports:
        - containerPort: 3040
          protocol: TCP
