apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-node
  name: feed-node
  namespace: default
spec:
  ports:
  - name: grpc
    port: 3020
  selector:
    app: feed-node
  type: ClusterIP
