apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: feed-node
  name: feed-node
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "20%"
  template:
    metadata:
      labels:
        app: feed-node
      name: feed-node
    spec:
      containers:
      - name: feed-node
        env:
        - name: COLOR_SERVER
          value: color-generator.default:4000
        image: sercand/demo-feed-node:1.16
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3020
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always

