apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: default
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: gateway
  type: LoadBalancer
