# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='feed.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x07\x66\x65\x65\x64.v1\"\\\n\x08\x46\x65\x65\x64Item\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x15\n\rprovider_name\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x05\"\x1f\n\x0e\x46\x65\x65\x64GetRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"3\n\x0f\x46\x65\x65\x64GetResponse\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.feed.v1.FeedItemB\x08Z\x06\x66\x65\x65\x64pbb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEEDITEM = _descriptor.Descriptor(
  name='FeedItem',
  full_name='feed.v1.FeedItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='feed.v1.FeedItem.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='feed.v1.FeedItem.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='feed.v1.FeedItem.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='provider_name', full_name='feed.v1.FeedItem.provider_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='feed.v1.FeedItem.score', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=117,
)


_FEEDGETREQUEST = _descriptor.Descriptor(
  name='FeedGetRequest',
  full_name='feed.v1.FeedGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='feed.v1.FeedGetRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=150,
)


_FEEDGETRESPONSE = _descriptor.Descriptor(
  name='FeedGetResponse',
  full_name='feed.v1.FeedGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='feed.v1.FeedGetResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=203,
)

_FEEDGETRESPONSE.fields_by_name['items'].message_type = _FEEDITEM
DESCRIPTOR.message_types_by_name['FeedItem'] = _FEEDITEM
DESCRIPTOR.message_types_by_name['FeedGetRequest'] = _FEEDGETREQUEST
DESCRIPTOR.message_types_by_name['FeedGetResponse'] = _FEEDGETRESPONSE

FeedItem = _reflection.GeneratedProtocolMessageType('FeedItem', (_message.Message,), dict(
  DESCRIPTOR = _FEEDITEM,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:feed.v1.FeedItem)
  ))
_sym_db.RegisterMessage(FeedItem)

FeedGetRequest = _reflection.GeneratedProtocolMessageType('FeedGetRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEEDGETREQUEST,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:feed.v1.FeedGetRequest)
  ))
_sym_db.RegisterMessage(FeedGetRequest)

FeedGetResponse = _reflection.GeneratedProtocolMessageType('FeedGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _FEEDGETRESPONSE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:feed.v1.FeedGetResponse)
  ))
_sym_db.RegisterMessage(FeedGetResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006feedpb'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
