apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-http
  name: demo-http
spec:
  type: "NodePort"
  ports:
    - name: http
      port: 3000
      nodePort: 31000
  selector:
    app: demo-http
